# Generated by Django 4.2.6 on 2023-10-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("darmstadt_termine", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("start_time", "end_time", "date", "creation_date")},
        ),
    ]
