# Generated by Django 4.2.7 on 2023-11-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("darmstadt_termine", "0007_alter_notification_last_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="language",
            field=models.CharField(default="de", max_length=10, verbose_name="Sprache"),
            preserve_default=False,
        ),
    ]
