# Generated by Django 4.2.7 on 2023-11-24 00:52

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("darmstadt_termine", "0008_notification_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmenttype",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Aktiv"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="minimum_waittime",
            field=models.DurationField(
                default=datetime.timedelta(seconds=300),
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.timedelta(seconds=60),
                        "Die Wartezeit muss mindestens 1 Minute betragen.",
                    )
                ],
                verbose_name="Mindest Wartezeit",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="token_verifier",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Token Verifier"
            ),
        ),
    ]
