# Generated by Django 4.2.11 on 2024-04-02 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("darmstadt_termine", "0012_department_location_appointment_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="darmstadt_termine.location",
                verbose_name="Ort",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentcategory",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_categories",
                to="darmstadt_termine.department",
                verbose_name="Abteilung",
            ),
        ),
        migrations.AlterField(
            model_name="appointmenttype",
            name="location",
            field=models.ManyToManyField(
                related_name="appointment_types",
                to="darmstadt_termine.location",
                verbose_name="Ort",
            ),
        ),
    ]
