# Generated by Django 4.2.11 on 2024-05-07 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("darmstadt_termine", "0016_notification_confirmed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="appointment_type",
            new_name="appointment_types",
        ),
    ]
