# Generated by Django 4.2.11 on 2024-05-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("darmstadt_termine", "0019_auto_20240507_0215"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="appointment_types",
        ),
    ]
