# Generated by Django 4.2.11 on 2024-05-07 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("darmstadt_termine", "0020_remove_appointment_appointment_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="darmstadt_termine.appointmenttype",
                verbose_name="Termintyp",
            ),
        ),
    ]
