# Generated by Django 4.2.11 on 2024-05-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("darmstadt_termine", "0021_alter_appointment_appointment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="scraper_run",
            field=models.ManyToManyField(
                related_name="appointments",
                to="darmstadt_termine.scraperrun",
                verbose_name="Scraperläufe",
            ),
        ),
    ]
