# Generated by Django 4.2.11 on 2024-05-08 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("darmstadt_termine", "0023_auto_20240507_1953"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="creation_date",
        ),
    ]
