# Generated by Django 4.2.7 on 2023-11-05 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darmstadtTermine', '0002_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='last_sent',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='Zuletzt gesendet'),
        ),
    ]
