# Generated by Django 4.2.7 on 2023-11-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("darmstadtTermine", "0003_alter_notification_last_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="active",
            field=models.BooleanField(default=False, verbose_name="Aktiviert"),
        ),
        migrations.AddField(
            model_name="notification",
            name="token_selector",
            field=models.CharField(
                default="", max_length=32, unique=True, verbose_name="Token Selector"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="token_verifier",
            field=models.CharField(
                default="", max_length=32, verbose_name="Token Verifier"
            ),
            preserve_default=False,
        ),
    ]
