# Generated by Django 4.2.7 on 2023-11-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "darmstadtTermine",
            "0004_notification_active_notification_token_selector_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="token_selector",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                unique=True,
                verbose_name="Token Selector",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="token_verifier",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Token Verifier"
            ),
        ),
    ]
